### ISSUE TITLE
Why is service_msgs added as a dependency?

### ISSUE THREAD

**Issue by Aposhian** [ouster-lidar/ouster-ros#113]
**Describe your question**
Why is `service_msgs` being pulled in as a dependency when it isn't being used? This package is only released on rolling, not even on humble, so it makes building on ROS LTS a little harder than it needs to be.

**Comment by Samahu** [comment]
The short answer, I am not sure. I probably added it because a PR I was working on failed during the build. I will open another pull request to check if is still required.

**Comment by Samahu** [comment]
`service_msgs` removed as a dependency
