### ISSUE TITLE
Specify param defaults for non-required params

### ISSUE THREAD

**Issue by Aposhian** [ouster-lidar/ouster-ros#120]
**Is your feature request related to a problem? Please describe.**
If parameters are not set when they are declared without a default, in ROS 2, this crashes the node.

**Describe the solution you'd like**
Any parameter that is not required to be set by the user (ex: udp_dest, mtp_main, metadata, etc.) should have a reasonable default value for the parameter.

**Describe alternatives you've considered**
The workaround is to set all params, and set unneeded ones to empty strings.

**Targeted Platform (please complete the following information only if applicable, otherwise dot N/A):**
- Ouster Sensor? N/A
- Ouster Firmware Version? N/A
- ROS version/distro? ROS 2 Humble
- Operating System? N/A
- Machine Architecture? N/A

**Comment by Samahu** [comment]
Addressed
