### ISSUE TITLE
unpack pointcloud2  in python

### ISSUE THREAD

**Issue by HaroldMurcia** [ouster-lidar/ouster-ros#121]
OS: Ubuntu 20.04
ROS Distro: Noetic
Python3.8.10
Platform: rosbag from OS1-128 

Hi,
I am interested in unpacking the poitcloud2 rostopic and converting it to numpy format:  {x,y,z,intensity,t,reflectivity,ring, ambient, range}  
![Screenshot from 2023-05-04 17-04-03](https://user-images.githubusercontent.com/15326731/236248790-f1d705f0-8b2c-43b3-bc3b-8bdab78ff9d1.png)

```
def callback_pointcloud2(msg):
        seq = msg.header.seq
        msg_time = msg.header.stamp.secs*1e9 + msg.header.stamp.nsecs
        # ouster cloud format
        points_list = []
        #  0 1 2    3      4      5         6       7       8
        # {x,y,z,intensity,t,reflectivity,ring, ambient, range}
```

Can you suggest an effective method to get all the information fields?

**Comment by HaroldMurcia** [comment]
Well, here a possibility:

```
    def callback_pointcloud2(self,msg):
        # ouster cloud format
        points_list = []
        #  0 1 2    3      4      5         6       7       8
        # {x,y,z,intensity,t,reflectivity,ring, ambient, range} 
        for data in pc2.read_points(msg, skip_nans=False):
            points_list.append(data)
        pc = np.array(points_list).astype(np.float32)
        pc[:,-1]=pc[:,-1]/1000  #range from mm to m
    # ...
```

**Comment by Samahu** [comment]
> Well, here a possibility:
> 
> ```
>     def callback_pointcloud2(self,msg):
>         # ouster cloud format
>         points_list = []
>         #  0 1 2    3      4      5         6       7       8
>         # {x,y,z,intensity,t,reflectivity,ring, ambient, range} 
>         for data in pc2.read_points(msg, skip_nans=False):
>             points_list.append(data)
>         pc = np.array(points_list).astype(np.float32)
>         pc[:,-1]=pc[:,-1]/1000  #range from mm to m
>     # ...
> ```

You've got it right, the order should match the same field order of our Point definition:
https://github.com/ouster-lidar/ouster-ros/blob/3c2b6a1bb0eca0b400106cce4ea978deff18a46d/include/ouster_ros/os_point.h#L33-L43
