### ISSUE TITLE
convert pcap to rosbag

### ISSUE THREAD

**Issue by tianshiz** [ouster-lidar/ouster-ros#13]
I see in the sdk that we can convert a pcap to csv. But is there a way to do this and convert to a rosbag with sensor_msg/PointCloud2 and sensor_msg/imu msg format?
If not, how do we take the row by row extracted in the csv demo and extract the imu and lidar data separately?

**Comment by nighthawk2032** [comment]
@Ali-Darzi  seems the code you were referring to does work, and seems to convert the ouster .pcap to .bag file properly..
maybe I am missing something, but 
rosbag play {the_created_bag_file}
doesn't enable me to create visualization on the RVIZ.. what am I doing wrong? is something missing in the process I am running?
(I can play other sampled .bag files and create their visualization on RVIZ properly)

**Comment by jeychandar** [comment]
Hey I wish ouster os1-32 with internal IMU should work but was happening is I convert pcap to rosbag and replay that using replay launch and record that bag. It seems that the visualization mapping is not working properly. It jitters a lot. I am not sure what was the problem. Could anyone help me out with this issue. Thanks in advance :)

**Comment by CantLooseToAMoose** [comment]
@Ali-Darzi 

> Conversion of Pcap to rosbag is doable using [this code](https://github.com/Krishtof-Korda/pcap-to-bag) to use it, clone the repo to the source folder of you Catkin workspace, the same workspace as ouster_example. After building, use ./pcap_to_bag to convert pcap to rosbag. To keep the output file size as small as possible, the output of os_node (which are imu_packets and lidar_packets) can be found in the rosbag file. To have the output of os_cloud_node (imu and PointCloud), the ouster_ros master should be running on another terminal. It will act as a translator that listens to the os_node.

Can you go into further detail on how to translate the created bag file to the right topic format? I am no expert in this field. Which launch file would i use for the "translation"? When I try to use replay.launch only the original topics do get replayed.
