### ISSUE TITLE
find_package: Could not find a package configuration file provided by "spdlog"

### ISSUE THREAD

**Issue by scottEpicWin** [ouster-lidar/ouster-ros#141]
**Describe the bug**
When I follow the directions in the README the build fails with the following error: 
`CMake Error at ouster-ros/ouster-sdk/ouster_client/CMakeLists.txt:5 (find_package):`
i will attach the full terminal and error logs to this post

**To Reproduce**
on a fresh ubuntu 18.04 desktop OS, 
installed melodic ROS through apt. as detailed in https://wiki.ros.org/melodic/Installation/Ubuntu
i clone the repo into ~/ros/ouster/catkin_ws/src/
i source the ROS distro with `source /opt/ros/melodic/setup.bash`
run the build command from ~/ros/ouster/catkin_ws/ `catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release`

**Platform (please complete the following information):**
- ROS version              = melodic
- Operating System      = Ubuntu 18.04.6 LTS
- Machine Architecture = x86_64
- using the most up to date repo.
- the sensor is not plugged in at this point, but it is an OS0-32

**terminal and files**
the full error is:
```
CMake Error at ouster-ros/ouster-sdk/ouster_client/CMakeLists.txt:5 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/dcm/ros/ouster/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/dcm/ros/ouster/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
dcm@ros-kudan:~/ros/ouster/catkin_ws$ 
```
[terminal.txt](https://github.com/ouster-lidar/ouster-ros/files/11497808/terminal.txt)

[CMakeOutput.log](https://github.com/ouster-lidar/ouster-ros/files/11497735/CMakeOutput.log)
[CMakeError.log](https://github.com/ouster-lidar/ouster-ros/files/11497736/CMakeError.log)

**Comment by Samahu** [comment]
The log states that spdlog is missing, you need to install the additional requirements stated in the driver [README.md](https://github.com/ouster-lidar/ouster-ros#requirements).
