### ISSUE TITLE
Cannot specify link libraries for target "GTest::gtest" which is not built by this project

### ISSUE THREAD

**Issue by BloodLemonS** [ouster-lidar/ouster-ros#142]
![image](https://github.com/ouster-lidar/ouster-ros/assets/56753880/b5fef5c1-14a0-4edd-ae47-b4b3f3bc3c90)
May I ask how to solve the following problems during build？

**Comment by Samahu** [comment]
This is is not tied to our build. It likely that any cmake project that you have on your machine will have the same problem.

Please try to install/re-install GoogleTest on the machine
```bash
sudo apt-get install libgtest-dev
```
and try to rebuild again (perform clean build).

**Comment by Samahu** [comment]
As I noted in my first response, the build error that you reported has nothing to do with our code or lack of proper requirements. Closing the issue.
