### ISSUE TITLE
customize the topic name

### ISSUE THREAD

**Issue by WyjFrogi** [ouster-lidar/ouster-ros#148]
Can the topic of lidar data only be /ouster/points? Is it possible to customize the topic name?

**Comment by Samahu** [comment]
It is not clear which version of ROS are you targeting, so I will answer in generic terms.

You can adjust the names of all topics of any particular node or component through remapping. Here is guides on how to implement in [ROS1](https://roboticsbackend.com/ros-topic-remap-example/) and in [ROS2](https://design.ros2.org/articles/static_remapping.html)
