### ISSUE TITLE
Change the format into velodyne format

### ISSUE THREAD

**Issue by yulan0215** [ouster-lidar/ouster-ros#15]
Hi everyone:

I am sorry that I am fresh and I would like to ask that how can I change the format of ouster into Velodyne like format. I found the code here:
<html>
<body>

void ouster_driver::OS1::convert2XYZIR | ( | const CloudOS1 & | in,
  |   | CloudOS1XYZIR & | out
  | )

but I did not know which code and which part of the code should I change, thx!

<br class="Apple-interchange-newline">
</body>
</html>void ouster_driver::OS1::convert2XYZIR	(	const [CloudOS1](http://docs.ros.org/en/melodic/api/ouster_driver/html/namespaceouster__driver_1_1OS1.html#a9455ea14ce69167cfdc9a34150a1fa31) & 	in,
[CloudOS1XYZIR](http://docs.ros.org/en/melodic/api/ouster_driver/html/namespaceouster__driver_1_1OS1.html#ac346ac2772c984d044b5d6c3d808b3fa) & 	out 
)

**Comment by StephenXIAOHK** [comment]
hi, I am also working with autoware.universe. Might I know is there any update about this workaround?

**Comment by Samahu** [comment]
Hi Stephan, I should have a PR soon. Thanks for your patience.
