### ISSUE TITLE
Running ouster driver in docker - "Must specify a sensor hostname"

### ISSUE THREAD

**Issue by LukasBergs** [ouster-lidar/ouster-ros#166]
Hi!

**Describe the bug**
I built the ouster driver within in a docker image but when I start the node I get the error message "Must specify a sensor hostname" even though it is set in the driver_params.yaml. I am sure that the launch file uses the correct params file. In https://github.com/ouster-lidar/ouster-ros/issues/159 I saw that you mentioned that there might be issues using docker. How can I fix this?

**Error message**
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-07-13-13-02-36-206028-lukas-113020
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [os_driver-1]: process started with pid [113052]
[ERROR] [launch_ros.actions.lifecycle_node]: Failed to make transition 'TRANSITION_CONFIGURE' for LifecycleNode '/kairosAB/ouster/os_driver'
[os_driver-1] [ERROR] [1689253356.546209244] [kairosAB.ouster.os_driver]: Must specify a sensor hostname
[os_driver-1] [ERROR] [1689253356.546462990] [kairosAB.ouster.os_driver]: exception thrown while configuring the sensor, details: Must specify a sensor hostname
[os_driver-1] [WARN] [1689253356.546552316] []: Error occurred while doing error handling.

**How to reproduce**
- Download the files that I use to build the image and run the docker container here: https://rwth-aachen.sciebo.de/s/eollHDl2k0LJfbZ
- Install tmux with `apt-get install tmux`
- Execute `bash docker_build.sh`
- Run the docker container using `bash docker_run/run_ouster_driver.sh` (eventually you have to make some changes here, especially the variables HOST_IP and HOST_NAME

**Video**
You can also find a video of the problem in the uploaded folder. 

**Platform:**
- Ouster Sensor: OS1-128
- Ouster Firmware Version: newest
- ROS version: humble
- Operating System: Ubuntu 22.04
- Machine Architecture: x64
- git branch: ros2

I would be very grateful for any help!
Lukas

**Comment by Samahu** [comment]
Hi @LukasBergs there is no issues using docker to run the ouster driver. I do suspect that the issue you are observing is a matter of wrong path supplied to the params_file. Is `/overlay_ws/src/custom_config_launch_files/config/driver_params.yaml` a valid path? Is it accessible within the container? I don't see that you mapped the path to `/overlay_ws` when you launch docker so how is it possible that you pass this file to the container?

**Comment by LukasBergs** [comment]
Hi @Samahu,
Thank you for your response! 

Within the docker build process I copy the content of the overlay workspace to the root directory of the image. In the attached video you can see that the node receives the params yaml file. If I make changes in it (e.g. syntax errors) I get an error message when starting the node. Nevertheless, it does not seem to receive the sensor_hostname parameter. 

Do you have any other guesses where the problem might be coming from?

Best
Lukas

**Comment by Samahu** [comment]
@LukasBergs when opting for a different ROS namespace for a node you config params file should reflect that too. Since you renamed the namespace you have to edit the config params files and prefix the node name with the modified namespace.

**Comment by LukasBergs** [comment]
Thanks a lot @Samahu !
I was not aware of that. After adjusting the namespace, the parameter is recognized by the ouster driver.
