### ISSUE TITLE
IPV4 do not show

### ISSUE THREAD

**Issue by zhangzirui1998** [ouster-lidar/ouster-ros#168]
![2023-07-16 21-37-38屏幕截图](https://github.com/ouster-lidar/ouster-ros/assets/67110568/c0fabaf2-4af1-4825-b59d-96d92ad980c0)
do not show IPv4，only show IPv6

**Comment by kairenw** [comment]
This Github answers - for support on connecting your sensors, contact our sensor support [here](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86)
