### ISSUE TITLE
In the state of high CPU load, the point cloud points are incomplete

### ISSUE THREAD

**Issue by cfzhous** [ouster-lidar/ouster-ros#17]
![image](https://user-images.githubusercontent.com/22591309/196696816-3fa0114e-58d5-43b1-a31e-ae2ee919637c.png)

**Comment by Samahu** [comment]
Hi @cfzhous,

Can you answer the following questions:
* How are you connected to the sensor, through Ethernet or WiFi?
* If it is Ethernet are you connected through an usb-ethernet adapter?
* Are you using a release build?
* I see that you have a process with high CPU usage, is this only due to the **ouster-ros** or is something else included.

**Comment by cfzhous** [comment]
Hi@Samahu 

- Connect the sensor directly via Ethernet
- Use the "catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release" command to compile the project
-  Test the CPU through "stress -c 5", and observe the situation of ouster under high CPU load. When the CPU is not fully loaded, there will be packet loss, and the packet loss will be more serious when the CPU is fully loaded.

**Comment by cfzhous** [comment]
> Hi@Samahu
> 
> * Connect the sensor directly via Ethernet
> * Use the "catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release" command to compile the project
> * Test the CPU through "stress -c 5", and observe the situation of ouster under high CPU load. When the CPU is not fully loaded, there will be packet loss, and the packet loss will be more serious when the CPU is fully loaded.

This is tested under Nvidia Xavier platform

**Comment by Samahu** [comment]
@cfzhous May I ask what ouster device that you are using and what is the version of the firmware. Also could run the command `sudo ethtool <NIC interface> | grep Speed` against the network interface that connects the sensor to get the interface speed.
 
I'll try to re-produce the issue and respond back.

**Comment by yongdengyinan** [comment]
The incomplete part of the points is missing or lost.  I would suggest running the ifconfig <ethernet interface> to check the RX dropped, if it remains 0, it means the lidar has sent all the data to the controller, and the packet drop problem is not caused by the lidar.

**Comment by cfzhous** [comment]
> @cfzhous May I ask what ouster device that you are using and what is the version of the firmware. Also could run the command `sudo ethtool <NIC interface> | grep Speed` against the network interface that connects the sensor to get the interface speed.
> 
> I'll try to re-produce the issue and respond back.

**Comment by cfzhous** [comment]
> @cfzhous May I ask what ouster device that you are using and what is the version of the firmware. Also could run the command `sudo ethtool <NIC interface> | grep Speed` against the network interface that connects the sensor to get the interface speed.
> 
> I'll try to re-produce the issue and respond back.
![20221021-185456](https://user-images.githubusercontent.com/22591309/197180685-7c1cdb38-989c-4496-a844-daab97716a43.png)

**Comment by cfzhous** [comment]
> > @cfzhous May I ask what ouster device that you are using and what is the version of the firmware. Also could run the command `sudo ethtool <NIC interface> | grep Speed` against the network interface that connects the sensor to get the interface speed.
> > I'll try to re-produce the issue and respond back.
> > ![20221021-185456](https://user-images.githubusercontent.com/22591309/197180685-7c1cdb38-989c-4496-a844-daab97716a43.png)

1000Mb/s

**Comment by Samahu** [comment]
Hi @cfzhous, thanks for the feedback. Could you try increasing the packet queue size as instructed [here](https://docs.nvidia.com/drive/driveworks-3.5/lidar_usecase3.html) and check if this helps with your case.

**Comment by Samahu** [comment]
@cfzhous I haven't heard back from you on this topic. In case you still have issue please try to update to the latest version of ouster-ros  and check if that helps with your situation. I will close this issue for now due to inactivity.
