### ISSUE TITLE
Cartesian coordinate system

### ISSUE THREAD

**Issue by Sisyphus-neo** [ouster-lidar/ouster-ros#173]
How to project the point cloud data of LiDAR onto the Cartesian coordinate system in ROS1 environment

**Comment by Samahu** [comment]
If you are subscribing to the **PointCloud2** message through the `/ouster/points` topic then the fields `x, y, z` represent the projected Cartesian coordinates.

**Comment by Sisyphus-neo** [comment]
It seems that the imu of ouster cannot output attitude information. I want to see whether the attitude information of external imu is needed for the transformation of laser radar coordinate to Local tangent plane coordinates, and then coordinate transformation can be performed

**Comment by Samahu** [comment]
You can achieve this by making the sensor a child to another object through a fixed link that has the altitude transformation. This mainly a ROS setup that can be achieved using the [TF package](http://wiki.ros.org/tf).

**Comment by Samahu** [comment]
The question is more of a pure ros question which can find better answers at https://discourse.ros.org/
