### ISSUE TITLE
Ros driver doesn't use correct udp_dest given by user during launch

### ISSUE THREAD

**Issue by SamuelSandvik** [ouster-lidar/ouster-ros#20]
https://github.com/ouster-lidar/ouster-ros/blob/4fb044db8d1f11fd3d50da96e0f0bb919fb9b4bb/src/os_sensor_nodelet.cpp#L155
Currently ros driver forces user to use set_udp_dest_auto instead of given udp_dest.

**Comment by Samahu** [comment]
Correct, we'll address this ASAP!
