### ISSUE TITLE
[ROS2] Process hangs on failure to connect to lidar

### ISSUE THREAD

**Issue by bertaveira** [ouster-lidar/ouster-ros#209]
**Describe the bug**
If it can't connect to the LiDAR then the process does not fully terminates and just hangs there. Seems to be because it does not do the transition from Configure to Activating so the event handler is still waiting.

This was also a problem in the old ros2_ouster_drivers repo but a quick fix would make it shutdown on fail. The same fix does not seem to work for this repo. The fix was to add an action of shutdown on node exit:
```
(...)
# Action added
emit_shutdown_action = launch.actions.Shutdown(reason='Ouster is shutting down...')

os_driver = LifecycleNode(
    package='ouster_ros',
    executable='os_driver',
    name=os_driver_name,
    namespace=ouster_ns,
    parameters=[params_file],
    output='screen',
    on_exit=[LogInfo(msg=["Ouster Driver stopped. Stopping everything..."]),
            emit_shutdown_action], # Added here!!!
)

(...)
```

This is one of the changes that was critical to us since the network card could sometimes take longer to start on boot and a full shutdown would cause the docker container to restart cleanly on its' own and recover. 

**Screenshots**
Terminal output:
<img width="1181" alt="image" src="https://github.com/ouster-lidar/ouster-ros/assets/9644729/a6e3ec83-a018-4a68-84b1-069d80a62857">

**Platform (please complete the following information):**
- ROS version/distro: Iron
- Operating System: Ubuntu 22.04 (also the docker image)
- Branch: ros2

**Comment by Samahu** [comment]
@bertaveira Please take a look at PR #211 which should address this issue.

**Comment by bertaveira** [comment]
Tested on my machine and seems to have the desired behaviour. Thank you!

**Comment by Samahu** [comment]
Perfect, thanks for the feedback!
