### ISSUE TITLE
os_sensor node error when trying to publish imu/lidar_packets (ros2-foxy)

### ISSUE THREAD

**Issue by tseco15** [ouster-lidar/ouster-ros#212]
**os_sensor node error when trying to publish imu/lidar_packets (ros2-foxy)**
We are working with ros2-foxy branch and we need lidar_packets topic. 
When we launch the node, we get the following warning:

[os_sensor-1] [WARN] [1694514333.922770617] [LifecyclePublisher]: Trying to publish message on the topic '/ouster/imu_packets', but the publisher is not activated
[os_sensor-1] [WARN] [1694514333.923958652] [LifecyclePublisher]: Trying to publish message on the topic '/ouster/lidar_packets', but the publisher is not activated

but os_sensor is configured and activated.

**To Reproduce**
In order to reproduce the bug, we launch the os_sensor by two different ways:
1. ros2 launch ouster_ros sensor.independent.launch.xml sensor_hostname:=192.168.1.60
Once the connection with the ouster lidar is established, the warnings arise. The /ouster/points are not published either. 

2. ros2 launch ouster_ros sensor.composite.launch.py
We change the value of sensor_hostname in os_sensor_cloud_image_params.yaml config file (default one), but the config file is not loaded correctly because an error arises:
[ouster.os_sensor]: Must specify a sensor hostname
Anyway, we set the sensor_hostname value manually in the source code, and after launching the previous launch file, the same message about the activation is  shown.

**Platform :**
- Ouster Sensor: OS-1-32-U1
- Ouster Firmware Version: v2.4.0
- ROS 2 foxy
- Ubuntu 20.04.5 LTS
- Jetson Xavier

**Comment by Samahu** [comment]
First time I have seen a complain about the topics are not activated, are using the latest commit.

```
ros2 launch ouster_ros sensor.composite.launch.py
We change the value of sensor_hostname in os_sensor_cloud_image_params.yaml config file (default one), but the config file is not loaded correctly because an error arises:
[ouster.os_sensor]: Must specify a sensor hostname
Anyway, we set the sensor_hostname value manually in the source code, and after launching the previous launch file, the same message about the activation is shown.
```

This error suggest that the file is not properly loaded or maybe the namespace/nodename combination does not match. Since you are using the default file, the path shouldn't have be the issue. So I am wondering if changed the node name?

**Comment by tseco15** [comment]
> First time I have seen a complain about the topics are not activated, are using the latest commit.

Thanks for your reply.
Regarding your comments:
- We are using the latest commit: commit 043d1a92cf47eaedc4a38818fe54f3a6adfcf581
- The combination namespace/nodename is the default one: /ouster/os_sensor. The configuration file also refers to this node
- This node is active, the connection is established, but the error about trying to publish imu/laser_packets is raised
- If we launch only os_driver node (using driver.launch.py), we get all the topics published by this node: points, imu and so on, but this node does not publish lidar_packets topic we need. For this reason, we tried with os_sensor node that publishes this topic
- We also tried exactly the same but with ROS Humble and ros2 branch and everything works properly, but unfortunately, our hardware platform only works with Ubuntu 20 (Jetson Xavier)

Any suggestions?

**Comment by Samahu** [comment]
@tseco15 This was a code issue that was inadvertently introduced by a previous merge. Please update to the latest commit for the `ros2-foxy` branch {package-version: 0.10.4} and this issue should be gone.

**Comment by tseco15** [comment]
> @tseco15 This was a code issue that was inadvertently introduced by a previous merge. Please update to the latest commit for the `ros2-foxy` branch {package-version: 0.10.4} and this issue should be gone.

Thank you very much! It works properly now.
The issue regarding the parameters file loading with sensor.composite.launch.py is not still solved, but it is not critical for us, we can work with any other launch file.
Thanks again!

**Comment by Samahu** [comment]
With regard to `sensor.composite.launch.py` I looked briefly into the issue and it seems related to node namespaces. Somehow Foxy does not work well when LifecycleNode is used along with composition and namespaces are used :man_shrugging: .
