### ISSUE TITLE
No points are received when using any launch file on OS-0

### ISSUE THREAD

**Issue by HelieD** [ouster-lidar/ouster-ros#220]
No points are published when using driver.launch, sensor.launch or record.launch

The program connects succesfully to the sensor and all the lidar infos are found 
`([ INFO] [1695292577.959556491]: ouster client version: 0.8.1+d730798-release product: OS-0-128, sn: 122146000978, firmware rev: v2.5.2 lidar mode: 1024x20, lidar udp profile: RNG15_RFL8_NIR8)`, but no points are sent.

The lidar is not defective, as points collection works on Python using the Ouster library.

Command used : `roslaunch ouster_ros driver.launch sensor_hostname:=169.254.198.165`

Also tested with the right udp ports, without change.

The RViz vizualisation is empty :

![image](https://github.com/ouster-lidar/ouster-ros/assets/83075905/14b7dca3-eaba-45eb-982d-410be6f40c0a)

The rosbag files produced when using record.launch only contains some sensor info (beam_intrinsics, imu_intrinsics, etc...) but no point data.
When using `rostopic echo` to view the messages sent on the different topics created, no message is seen.

    Platform : OS-0 rev. D
    FW : 2.5.2
    ROS Noetic
    Linux Ubuntu 20.04 on WSL2, x64, Nvidia Quadro P520
    Latest version of ROS_Ouster, installed with catkin using the provided guide

--------
[log.txt](https://github.com/ouster-lidar/ouster-ros/files/12683537/log.txt)

**Comment by Samahu** [comment]
@HelieD Didn't you just confirm that using local ip worked in the other  #219

**Comment by HelieD** [comment]
That was an other issue, so i opened a new one. Now, the lidar is reached but no points are received.

**Comment by Samahu** [comment]
Closing this issue due to no inactivity. Feel free to re-open if you still having the issue.
