### ISSUE TITLE
ros topic delay increasing with time

### ISSUE THREAD

**Issue by Jaetriel** [ouster-lidar/ouster-ros#226]
Hi, I've got an OS1-128 using the latest version of the firmware. Running the ROS node at 2048x10 mode synced with a Jetson AGX via hardware PTP, the results of `rostopic delay /os_cloud_node/points` command start from around 0.140 sec, but over the course of about 10-15 mins slowly progress to 0.250~ (which feels like quite a lot) and then it seems like they kinda slowly fluctuate between the two. What are the possible reasons and is there a way to make the delay more stable?

**Comment by Samahu** [comment]
First of all, are you using the latest version of the driver? also try using the new `driver.launch.py` to launch the driver. You should observe a significant drop in the message delay with no delay.
