### ISSUE TITLE
Consider changing `ptp_utc_tai_offset` default value

### ISSUE THREAD

**Issue by lowellausen** [ouster-lidar/ouster-ros#231]
**Describe your question**
A clear and concise description of your question.

Hello! Opening this issue here as an idea/suggestion :pray: 

Should  the default value for the new `ptp_utc_tai_offset` parameter (introduced here https://github.com/ouster-lidar/ouster-ros/pull/195)  be set to `0.0`?

We had our PTP synchronization working nicely (I think we followed this at some point https://github.com/ouster-lidar/ouster_example/issues/144), and after pulling the latest updates we had to look into the changelog to figure that we needed to change the aforementioned parameter from `-37.0` to `0.0` for our synchronization to work properly again.

My idea would be to set this to `0.0` so
1. It doesn't automatically "break" the system for people who pull the latest changes 
2. It removes the need to change all the `-37.0`s when a new leap second is added   

I can open a PR if we agree to some possible change on this issue!

Thanks for the attention!

**Platform (please complete the following information):**
- Ouster Sensor? OS-0 32 Rev D 
- Ouster Firmware Version?  2.5.2.
- ROS version/distro? Humble
- Operating System? Ubuntu 22.04 based ros:humble Docker image
- Machine Architecture? x64
- git commit hash: https://github.com/ouster-lidar/ouster-ros/pull/195

**Comment by lowellausen** [comment]
Hi @Samahu, thanks for your answer! 

I understand your point and I agree, it is easy to adapt to this change as it is. With the upcoming breaking change indication in the changelog this will be quite clear! :ok_hand: 

Will close this one, since the proposed solution is underway. Thanks!

**Comment by Hommus** [comment]
@Samahu I came across this issue and would like to suggest adding a note to the [Ouster PTP Quickstart Guide](https://static.ouster.dev/sensor-docs/image_route1/image_route2/appendix/ptp-quickstart.html) to help those in a similar situation in the future.

**Comment by Samahu** [comment]
That's a good note. I will check with the page editor if they can add such a note.
