### ISSUE TITLE
OS1 Intensity and Reflectivity Units

### ISSUE THREAD

**Issue by poledna** [ouster-lidar/ouster-ros#234]
**Describe your question**
Hello, 
I would like to know the unit values of the Intensity and Reflectivity.
On this topic i would like also to know what would a value of intensity of 0 could mean.
If this info is readily available please point me to it, and sorry for the inconvenience.
Resources I  have checked: Datasheet,  HW and SW User Manual.
Thank you,
Yuri

**Platform (please complete the following information):**
- Ouster Sensor? OS-1
- ROS version/distro? noetic
- Operating System? Linux
- Machine Architecture? x64, 
- git commit hash 3c2b6a1bb0eca0b400106cce4ea978deff18a46d

**Comment by Samahu** [comment]
Intensity corresponds to signal which is the number of photons collected by the sensor for a pixel during a single cycle. Thus a zero would mean no photos were detected during the cycle for the specific pixel.

For reflectivity you can refer to my previous answer: https://github.com/ouster-lidar/ouster_example/issues/412
