### ISSUE TITLE
`RAW` option for proc_mask

### ISSUE THREAD

**Issue by Grisly00** [ouster-lidar/ouster-ros#238]
**Is your feature request related to a problem? Please describe.**
At the moment I am switching back and forth between the different XML and Python launch files. As far as I understand the preferred approach in the future would be to use `driver.launch.py`. The problem for me is that it does not publish raw lidar_packets which I like to record.

**Describe the solution you'd like**
Would it be possible to add another key to proc_mask like `RAW` to publish raw lidar_packets?

**Describe alternatives you've considered**
At the moment I simply use `sensor.independent.launch.py`. (`sensor.independent.launch.xml` gave me recently some errors as described in this issue #159.)

**Targeted Platform (please complete the following information only if applicable, otherwise dot N/A):**
- ROS version/distro? ROS2 humble
- Operating System? Jammy
- Machine Architecture? ARM

**Comment by Samahu** [comment]
Yes, we do plan on providing a python versions for record/replay launch files..

**Comment by Grisly00** [comment]
@Samahu: Thanks, but this does not really answer my question. 
To rephrase, is it possible to provide a `RAW` option to `proc_mask` so we can record lidar_packets with `driver.launch.py` launch file, or will `sensor.independent.launch.py` be the way to go also in future?

**Comment by Samahu** [comment]
Got it. It is the same as #251
