### ISSUE TITLE
laserscan is not correctly

### ISSUE THREAD

**Issue by adridelta** [ouster-lidar/ouster-ros#239]
**Describe the bug**
Laserscan does not publish data correctly. there are only a few point when using /ouster/scan. PointCloud data is present and published correctly

i also tried some of the solutions like '196 but it didn't work

**To Reproduce**
ros2 launch ouster_ros driver.launch.py

**Screenshots**
![Screenshot from 2023-10-24 10-01-06](https://github.com/ouster-lidar/ouster-ros/assets/124087297/1ec2bb5c-f4ea-41e7-b4e6-51b93fdf531f)
![Screenshot from 2023-10-24 10-01-23](https://github.com/ouster-lidar/ouster-ros/assets/124087297/39ecbbc4-2fad-4dc6-853a-8f8532364da5)

**Platform (please complete the following information):**
- Ouster Sensor? OS1-32-U
- Ouster Firmware Version? 2.4
- ROS version/distro? \foxy
- Operating System? Ubuntu 20.04
- Machine Architecture? x64
- git commit hash (if not the latest).

**Comment by Samahu** [comment]
@adridelta just to make sure, did you set the `scan_ring` to an appropriate value? For an OS1-32-U you should be using a value of 16?

**Comment by Samahu** [comment]
Resolved by #204
