### ISSUE TITLE
Bring back optional publishing of lidar and imu packets to new single nodelet driver

### ISSUE THREAD

**Issue by skohlbr** [ouster-lidar/ouster-ros#251]
**Is your feature request related to a problem? Please describe.**
We recently upgraded to use the new single nodelet driver (started via driver.launch as described in https://github.com/ouster-lidar/ouster-ros#sensor-mode ). This shows significantly reduced CPU consumption on Jetson embedded systems compared to the "old" multi-nodelet setup. However, it appears the support to simultaneously publish the lidar and imu packets has been dropped. This is a problem because for data recording purposes, those are the most useful data to record (as also remarked by others in https://github.com/ouster-lidar/ouster-ros/issues/110 ).

**Describe the solution you'd like**
It would be great to have the single driver nodelet also optionally (i.e. `if numSubscribers() > 0` ) publish the raw packets, so they can be recorded for later postprocessing/analysis.

**Describe alternatives you've considered**
An alternative is using the old multi-nodelet setup, but that one causes high CPU load on Jetson embedded systems, so not a good option.

**Targeted Platform (please complete the following information only if applicable, otherwise dot N/A):**
- ROS1, but likely applies to ROS2 also (?)

**Comment by Samahu** [comment]
Same as #238

**Comment by skohlbr** [comment]
@Samahu can you provide an indication if this is in the works or what the plans are wrt this feature?
