### ISSUE TITLE
Ouster Data Quality Issues

### ISSUE THREAD

**Issue by satyajitghana** [ouster-lidar/ouster-ros#256]
I have a OS1-32

Today i was just collecting some static data, no movement, just static

![image](https://github.com/ouster-lidar/ouster-ros/assets/8092481/b6802894-a1e9-4d2d-956f-36e6ab3d0f21)

![image](https://github.com/ouster-lidar/ouster-ros/assets/8092481/155b44b1-110a-4ec7-b4aa-4a6ee3e31255)

![image](https://github.com/ouster-lidar/ouster-ros/assets/8092481/e6c1955d-bc70-48b0-9fd6-40fbe8fd6ac9)

![image](https://github.com/ouster-lidar/ouster-ros/assets/8092481/9014d5aa-8e62-4b3b-bee5-837358c42059)

The Point Cloud is really weird, it like streaks of points. instead of a single point.

Ideally we expect noise in the points, but not like this, it should have been a grid of points, not a grid of streak lines. Its like a smudged Image.

this was resulting in a very thick point cloud if we do any sort of SLAM.

So we were just taking a a look at the RAW data.

Is this normal?

**Comment by Samahu** [comment]
What kind of visualizer are you using to represent the LidarScan? Is this coming through RVIZ

**Comment by satyajitghana** [comment]
Yes this is coming from RVIZ. So we've kept the LiDAR static and recorded bag file. Converted to PCD. I was thinking this could be due to vibrations. But looking at the pattern it doesn't seem so. It looks like something is wrong in the LiDAR output

**Comment by Samahu** [comment]
I have never seen such an output on RVIZ, I advise you to open a [support ticket](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86)  because there could be some hardware issue at play. (and share the bag file for in-depth analysis of the problem).

**Comment by Samahu** [comment]
@satyajitghana I don't see this to be a software problem but could a hardware issue. Please open a support ticket and link this PR to it.
