### ISSUE TITLE
Ros2 code sneaked into ros1 version of driver

### ISSUE THREAD

**Issue by ovaag** [ouster-lidar/ouster-ros#266]
**Describe the bug**
Just noticed that in https://github.com/ouster-lidar/ouster-ros/pull/253/files, a new `ouster-ros` directory with some ros2 version of the os_driver_nodelet is now present in the current master (https://github.com/ouster-lidar/ouster-ros/blob/master/ouster-ros/src/os_driver_node.cpp).

**To Reproduce**
Stare at folders in root directory of https://github.com/ouster-lidar/ouster-ros and notice that there is an extra ouster-ros folder with ros2 code

**Screenshots**
![image](https://github.com/ouster-lidar/ouster-ros/assets/50892582/36e7fd15-680b-42c8-a0da-38283f6e90ff)

- git commit hash 4b433325e77e7af176901433b34174f09d53392f

**Comment by Samahu** [comment]
You are absolutely right :man_facepalming: , will address immediately!
