### ISSUE TITLE
Dockerfile build error

### ISSUE THREAD

**Issue by zhengdal** [ouster-lidar/ouster-ros#271]
**Describe the bug**
Got error when trying to build the dockerfile in this repository

**To Reproduce**
Steps to reproduce the behavior (steps below are just an example):
1. change "ROS_DISTRO=melodic" to "ROS_DISTRO=noetic" in the dockerfile.
2. execute "sudo docker build -t ouster_ros ." under the root directory of the repository
3. Cmake Error occurs within catkin_make:
  #0 2.377 CMake Error at ouster-ros/CMakeLists.txt:4 (include):
  #0 2.377   include could not find load file:
  #0 2.377 
  #0 2.377     DefaultBuildType

**Screenshots**
![Screenshot from 2023-11-28 15-46-27](https://github.com/ouster-lidar/ouster-ros/assets/123930431/b1b886c9-7d6c-44a3-ba6e-dee4e06c5596)

**Platform (please complete the following information):**
- ROS version/distro: noetic
- Operating System: Ubuntu 20.04
- Machine Architecture: x64

**Comment by Samahu** [comment]
@zhengdal Did you follow the described instruction stated in the [Getting Started](https://github.com/ouster-lidar/ouster-ros#getting-started) section? You need to clone with `recurse-submodule` flag set. I think this mostly what is the error is all about.
