### ISSUE TITLE
Synchronize ouster and camera

### ISSUE THREAD

**Issue by giangdao1402** [ouster-lidar/ouster-ros#275]
- OS1-16
- ROS noetic
- How can i sync ouster lidar and camera ?

**Comment by Samahu** [comment]
* If your camera supports PTP time protocol then look into utilizing PTP timestamp mode; [Ouster's PTP quickstart guide](https://static.ouster.dev/sensor-docs/image_route1/image_route2/appendix/ptp-quickstart.html) provides sufficient information. Ideally make use of a hardware PTP clock.
* If your camera doesn't support PTP (or as an alternative to using PTP mode), it is likely that your camera has some connectors to support camera trigger on an incoming pulse generated by a device. I think [our guide about GPS/GNSS Synchronization](https://static.ouster.dev/sensor-docs/gps_guide/gps_guide.html) provides some useful information to that regard. 
* Finally, look into [Message Filter Time Synchronization API](https://wiki.ros.org/message_filters#Time_Synchronizer).


Hope this helps
