### ISSUE TITLE
ROS2 multi-casting, multiple processes listening to single LiDAR

### ISSUE THREAD

**Issue by mgow001** [ouster-lidar/ouster-ros#28]
Hello, 

Could you please provide an example ROS2 launch file for starting Ouster LiDAR in multi-casting mode so multiple processes can listen to the messages? My LiDAR model is OS1-64. 

Thank you!

**Comment by mgow001** [comment]
Hello, just writing to follow-up on this. If ROS2 launch example is not available right now maybe you can provide guidelines on how to enable multi-casting for Ouster Lidar so multiple process can listen to the data stream? Thanks!

**Comment by Samahu** [comment]
@mgow001 At some point one of our community member submitted a PR against our ouster ROS 1 driver: https://github.com/ouster-lidar/ouster_example/pull/278. It is an old PR but maybe you will find it useful.

**Comment by mgow001** [comment]
Thanks @Samahu, I had a look earlier at that PR but I could not make much out of it unfortunately. It would be great to get more detailed multi-casting description if possible. Thanks!

**Comment by Samahu** [comment]
There will be some time before we can get to this. But I will keep this issue open.

**Comment by Samahu** [comment]
@mgow001 I am working with @ShepelIlya to merge the PR #57, it does work as described but it may benefit some doc which we will get to once we finalize the merge request.
