### ISSUE TITLE
Colcon build failed on Ubuntu 22.04 ROS2 Humble

### ISSUE THREAD

**Issue by kushal2507** [ouster-lidar/ouster-ros#283]
**Describe your question**
I am unable to successfully build the package on ros2 humble, Ubuntu 22.04. I have installed the dependencies as listed on the page and also ran rosdep install. I have also run apt update before 

Here are the steps I am undertaking, hopefully someone can reproduce the problem : 

- cd ros2_ws/src
- git clone --recurse-submodules https://github.com/ouster-lidar/ouster-ros.git
- git checkout ros2
- colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

Error attached below

**Screenshots**
![Screenshot from 2024-01-29 14-40-26](https://github.com/ouster-lidar/ouster-ros/assets/37099358/23d20c99-be43-4f24-8fab-fd6fd9739bab)

**Platform (please complete the following information):**
- ROS version/distro \[humble]
- Operating System \[Ubuntu 22.04\]

**Comment by kushal2507** [comment]
I added the dependency libglfw3 by running 

`apt install libglfw3-dev`

But now I am getting the following error : 

![Screenshot from 2024-01-29 15-02-03](https://github.com/ouster-lidar/ouster-ros/assets/37099358/e0e8ba6e-b609-45aa-9246-84cceabb76e9)

**Comment by hehonglu123** [comment]
Just encountered the same problem, make sure you have the `ouster-sdk` [submodule](https://github.com/ouster-lidar/ouster_example/tree/2898060fb47a69b4fbf9807d3c17f6fdc8249379)  2898060 at `<ws>/src/ouster_ros/ouster_ros/ouster_sdk/`.

The full build command from Action is `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations"`

**Comment by kushal2507** [comment]
@hehonglu123 thank you for your response. I was able to resolve this sometime back using the same.
