### ISSUE TITLE
Where and when is the timestamp generated?

### ISSUE THREAD

**Issue by MarioSpeckert** [ouster-lidar/ouster-ros#299]
Hello,
we have an Ouster OS1-128 Rev.7 FW:v3.0.1 with ROS Noetic on Ubuntu 20.04 x64.
To synchronize the Lidar data with cameras triggered by the sync-out signal, we need to know where and when the timestamp from the ROS message is created.
Suppose the LIDAR is at 0 degrees and the new phase lock signal is generated:
- Is the timestamp generated by the LIDAR or by the ROS node on the host?
- What angle in the message does the timestamp refer to (beginning, end, or somewhere in between)?

Thank you.

**Comment by Samahu** [comment]
The ouster-ros driver has 4 timestamp modes as listed in the [launch files](https://github.com/ouster-lidar/ouster-ros/blob/5a08f89e21dabfb78ae359f9bfc4ba869a275104/launch/driver.launch#L23-L26). The first 3 modes are sensor timestamp mode and the driver uses the value provided by the sensor. You can refer to the sensor documentation about these modes. If you have PTP setup properly then the timestamp will refer to the master lock. The last mode overrides the Scan with ROS timestamp. In all of these modes the message timestamps refers to the beginning of the LidarScan.

Hope this answers your question.
