### ISSUE TITLE
deprecated declarations

### ISSUE THREAD

**Issue by grischi** [ouster-lidar/ouster-ros#304]
**Describe the bug**
When compiling the ros2 branch with Ubuntu 22.04 & ros2 humble, gcc (11.4) prints several deprecated declaration warnings

**To Reproduce**
1. clone this repo and its submodules to a ros2 workspace
2. source /opt/ros/humble/setup.bash
3. colcon build --packages-up-to ouster_ros --event-handler console_direct+

**Screenshots**

**Platform (please complete the following information):**
- Ouster Sensor? not relevant
- Ouster Firmware Version? not relevant
- ROS version/distro? humble
- Operating System? Ubuntu Linux 22.04
- Machine Architecture? x86-64
- git commit hash (if not the latest). 11287a9

**Comment by kbiesiadecki141** [comment]
I am also having this issue on Ubuntu 22.04. Any suggestions?

**Comment by Samahu** [comment]
Hi @kbiesiadecki141,

all of the these deprecations will be resolved in the upcoming ouster-ros release. However, in the meantime you can try adding `-DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-deprecated"` to your build command. In other words:
 
```bash
colcon build ouster_ros --cmake-args -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-deprecated"
```
