### ISSUE TITLE
 The problem of point cloud rotation depending on the installation angle of LiDAR

### ISSUE THREAD

**Issue by CYJ00** [ouster-lidar/ouster-ros#307]
Hello.
I have probelm with the angle of LiDAR.

When the LiDAR is installed at a 90-degree angle to the ground, as shown in the attached video visualized in ROS, the generated point cloud is rotated to match the same orientation as when the LiDAR is installed parallel to the ground.

https://github.com/ouster-lidar/ouster-ros/assets/126875107/ee6457bd-0c10-4fe5-a331-f58a8204f30b

<img width="529" alt="KakaoTalk_20240304_104021413" src="https://github.com/ouster-lidar/ouster-ros/assets/126875107/72e8a82a-77fb-4d19-91cf-875f7d9376fa">

Could you provide some insights on why this rotation occurs and suggest possible solutions to solove this issue?

**Platform (please complete the following information):**
- Ouster Sensor? OSDome
- Ouster Firmware Version?  v3.0.1
- ROS version/distro? noetic
- Operating System? Ubuntu 20.04
- Machine Architecture? x64
- git commit hash (if not the latest).

**Comment by Samahu** [comment]
I think this mainly depends on your have configured the links within your setup, you probably have some parent link to the sensor which is contributing to the rotation. I don't think we can comment or help much since this is your own setup.
