### ISSUE TITLE
How can I get an absolute unix timestamp to use for time synchronization with other sensors.

### ISSUE THREAD

**Issue by lyxichigoichie** [ouster-lidar/ouster-ros#310]
The ouster-ros driver has 4 timestamp modes as listed in the [launch files](https://github.com/ouster-lidar/ouster-ros/blob/5a08f89e21dabfb78ae359f9bfc4ba869a275104/launch/driver.launch#L23-L26). The first 3 modes are sensor timestamp mode and the driver uses the value provided by the sensor. You can refer to the sensor documentation about these modes. If you have PTP setup properly then the timestamp will refer to the master lock. The last mode overrides the Scan with ROS timestamp. In all of these modes the message timestamps refers to the beginning of the LidarScan.

How can I get an absolute unix timestamp to use for time synchronization with other sensors.

_Originally posted by @Samahu in https://github.com/ouster-lidar/ouster-ros/issues/299#issuecomment-1954567518_

**Comment by Samahu** [comment]
We report the messages timestamp using `ros::Time` which composed of seconds and nanoseconds, which can then be converted into Linux time. Consult Ouster documentation on the different synchronization modes and pick the one that fits your setup.
