### ISSUE TITLE
Lidar/GPS Synchronisation problem

### ISSUE THREAD

**Issue by jiheddachraoui** [ouster-lidar/ouster-ros#311]
Hello,
I'm looking to set up the LiDAR to receive timestamps directly from the GPS/GNSS. I've been following this tutorial: https://forum.ouster.at/d/74-how-to-synchronize-gps-with-ouster-sensor-rev-d .
However, when I read the timestamp from the ROS message, it starts from 0 increments to 4, then resets back to 0, looping like that. Can't figure out why.

This is the **config** of the lidar:
```
{
    "azimuth_window": [0, 360000],
    "columns_per_packet": 16,
    "lidar_mode": "1024x20",
    "multipurpose_io_mode": "INPUT_NMEA_UART",
    "nmea_baud_rate": "BAUD_9600",
    "nmea_ignore_valid_char": 0,
    "nmea_in_polarity": "ACTIVE_HIGH",
    "nmea_leap_seconds": 18,
    "operating_mode": "NORMAL",
    "phase_lock_enable": false,
    "phase_lock_offset": 0,
    "signal_multiplier": 1,
    "sync_pulse_in_polarity": "ACTIVE_HIGH",
    "sync_pulse_out_angle": 360,
    "sync_pulse_out_frequency": 1,
    "sync_pulse_out_polarity": "ACTIVE_HIGH",
    "sync_pulse_out_pulse_width": 0,
    "timestamp_mode": "TIME_FROM_SYNC_PULSE_IN",
    "udp_dest": "169.254.218.214",
    "udp_port_imu": 7503,
    "udp_port_lidar": 7502,
    "udp_profile_imu": "LEGACY",
    "udp_profile_lidar": "LEGACY"
}

```

**Platform :**
- Ouster Sensor: OS-1-64-U13
- Ouster Firmware Version: v2.4.0
- ROS version/distro: ROS1 noetic
- Operating System: Linux
- Machine Architecture: x86_64

**Comment by Samahu** [comment]
This question is beyond the scope of this Github project, please reach out to [Ouster Technical Support Team](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86) and they'd be able to help.
