### ISSUE TITLE
Reconnection to sensor

### ISSUE THREAD

**Issue by evehult** [ouster-lidar/ouster-ros#332]
Hi,
I'm planning to use the Ouster driver in a project and I am interested to know how the driver handles reconnection. 

1. How does the driver behave if it has initialized a sensor and moved to active (lifecycle) state, but then looses connection due to, e.g., power loss? 
2. Does the driver detect and/or alert when it looses connection? If not, is this a feature that you are planning to develop?

Thanks!

**Comment by Samahu** [comment]
Hi @evehult, sorry for the delayed response but currently the driver doesn't handle re-connection if the sensor loses power or network is disconnected. But one of our community members made a contribution a while back to this regard which I aim to look into soon and integrate in the driver, you may check it out here https://github.com/ouster-lidar/ouster-ros/pull/119 and see if covers your use case.

**Comment by evehult** [comment]
No worries, thank you for the reply @Samahu! The contribution you referred to looks promising for our use case and I will look into it. Regarding integrating it into the driver, do you have any idea about when that work will be initiated? I understand it may be hard to determine, but I wanted to ask anyway since if it is soon, then maybe my team and I will have time to wait for the integration.
