### ISSUE TITLE
Where are the timestamps from the ROS messages coming from?

### ISSUE THREAD

**Issue by louis-wiesmann** [ouster-lidar/ouster-ros#34]
Hello, we are using the ROS the driver to obtain the point cloud data. For the the time synchronization we are using `TIME_FROM_PTP_1588`. We are wondering where the timestamp from the PointCloud2 message is coming from? Is it from the ptp synched sensor (e.g. start of the measurement process) or the timestamp when the message is received on the host machine, or is it the time after the ROS driver processed the packets?

**Comment by Samahu** [comment]
> The reason why we ask is that we see time synchronization problems when running in full resolution mode (2048x10) and recording it to a rosbag. We thought that it might be a problem due to the increased cpu usage which leads to a delay in the processing. But this should not be a problem if the timestamp is directly coming from the sensor

Yeah, it shouldn't. But first make sure that your sensor and machine are running in sync. I would suggest that you use the **IMU** sensor message to check if your nodes are out of sync. The estimated delay of IMU messages is about 1 ms delay (2-3 ms at most).

**Comment by Samahu** [comment]
@louis-wiesmann I hope that I have fully answered your questions, since I haven't heard back from you I will close the issue. Let's us know if you have further concerns.

**Comment by louis-wiesmann** [comment]
Thank you very much! Yes this was very helpful.
