### ISSUE TITLE
I can't access the topic /ouster/imu

### ISSUE THREAD

**Issue by andressaff** [ouster-lidar/ouster-ros#38]
HI everyone, 

I can't access the topic` /ouster/imu` as a image, but the point cloud is working normally
![graph](https://user-images.githubusercontent.com/53279689/206531001-c62214f2-a09a-43b1-be94-d564b486e8f2.png)

**Comment by Samahu** [comment]
Hi @andressaff,

There are two things at play here:
* Are you connected successfully to the sensor imu? meaning imu packets are successfully sent by the sensor to ouster-ros driver. You can verify this by running `rostopic hz /ouster/imu_packets`.
* The other thing you have to create subscription to `/ouster/imu` in order for it to show up on the rqt graph tool. Launch the sensor node, run the command: `rostopic hz /ouster/imu` in a separate terminal, then launch rqt graph and the topic should be displayed.

**Comment by Samahu** [comment]
I didn't hear back from you @andressaff .. hope my answer helped .. closing the issue.
