### ISSUE TITLE
typo in record.launch

### ISSUE THREAD

**Issue by retepik** [ouster-lidar/ouster-ros#398]
please repair on line 130 <a**e**g name="pub_static_tf" to <a**r**g name="pub_static_tf" in record.launch

**Comment by retepik** [comment]
also record.launch don't work because cannot run common.launch, it need arguments: organized, destagger, min_range, max_range

**Comment by Samahu** [comment]
Hi @retepik thanks for reporting this. I will fix it ASAP.
