### ISSUE TITLE
I can't access the topic /ouster/points

### ISSUE THREAD

**Issue by andressaff** [ouster-lidar/ouster-ros#41]
HI everyone,

I can access the topic `/ouster/points` and I can visualize on the RVIZ, but I want to use on Fast LIO and the topic `/ouster/points` don't subscriber at `/laserMapping`. I achieved to run command: `rostopic hz /ouster/lidar_packets` and `rostopic hz /ouster/points`
![sensor](https://user-images.githubusercontent.com/53279689/207385398-e8212ebf-8a39-4005-9693-e20c2e7d319f.png)

**Comment by Samahu** [comment]
Hi @andressaff,

I did look briefly into this issue and it seems that **FAST_LIO** didn't update topics names after we renamed them back in August. After correcting the topics names and running **FAST_LIO** it should run successfully as illustrated in the graph below:
![image](https://user-images.githubusercontent.com/606033/208201471-7093d1f1-894d-4c6d-8740-7e9a43036074.png)

I did submit a PR to the **FAST_LIO** repository to address the issue: https://github.com/hku-mars/FAST_LIO/pull/205
