### ISSUE TITLE
Getting PPS NMEA time sync status

### ISSUE THREAD

**Issue by hirenpatel1207** [ouster-lidar/ouster-ros#45]
I have an OS1-Rev7 sensor. We plan to use time sync via NMEA messaging the ouster guide mentions that we can check the sync status on the sensor via TCP command "get_time_info". https://static.ouster.dev/sensor-docs/gps_guide/gps_guide.html
I was wondering how it can be achieved through ros interface. Is there any ROS service which can give this info?

**Comment by Samahu** [comment]
Hi @hirenpatel1207, unfortunately, we don't have this information accessible via a ROS service currently. You can access it through the provided tcp interface as you mentioned. As an alternative I think you can access it via http requests to the sensor too.
