### ISSUE TITLE
Do you plan to release APT packages for the ROS2 Rolling driver?

### ISSUE THREAD

**Issue by hodnajit** [ouster-lidar/ouster-ros#69]
Hi,

Are there any plans to release the APT packages for the ouster driver? :)

For ros:rolling, there is already published APT package ouster_msgs. Are there any plans to deal with that?

https://github.com/ros-drivers/ros2_ouster_drivers/issues/131

Thanks for you work :)

Best regards Jitka Hodna

**Comment by Samahu** [comment]
Yes, we do have plans to create and distribute pre-built binaries (deb) of the official driver. I am aware of the current ouster ros2 debian which is something that to be resolved.

**Comment by hodnajit** [comment]
thanks :) looking forward to have them :)
