### ISSUE TITLE
os_cloud does not provide a 'secondary return pointcloud' when configured for dual return mode. (ros2-foxy)

### ISSUE THREAD

**Issue by MPeebles** [ouster-lidar/ouster-ros#71]
Both the base `OusterProcessingNodeBase` and derived  `OusterCloud` classes declare `sensor::sensor_info info;`

When `OusterCloud::on_init()` is called:

```cpp
    void on_init() {
        declare_parameters();
        parse_parameters();
        auto metadata = get_metadata();
        info = sensor::parse_metadata(metadata);
        n_returns = get_n_returns();
        create_lidarscan_objects();
        create_publishers();
        create_subscriptions();
    }
```
`info` refers to the object defined in `OusterCloud`, however inside the `OusterProcessingNodeBase::get_n_returns()` method:

```cpp
int OusterProcessingNodeBase::get_n_returns() {
    return info.format.udp_profile_lidar ==
                   UDPProfileLidar::PROFILE_RNG19_RFL8_SIG16_NIR16_DUAL
               ? 2
               : 1;
}
```

`info` refers to the object defined in `OusterProcessingNodeBase`. 

This means that `get_n_returns` is operating on an un-configured version of the `info` object, which results in `n_returns` not being set correctly when using a dual return config.

I have worked around this issue by removing the `info` object from `OusterCloud` (line 201 os_cloud_node.cpp)
I also required changes to the `ouster-sdk` submodule due to [this issue](https://github.com/ouster-lidar/ouster_example/issues/489)

**Comment by Samahu** [comment]
You are absolutely right, this was overlooked during the refactoring of **os_image** and **os_cloud**. Thanks for reporting the issue. I have removed the duplicate `sensor::sensor_info` object.
