### ISSUE TITLE
drop-out messages 

### ISSUE THREAD

**Issue by SFakoorian0111** [ouster-lidar/ouster-ros#75]
I am using the latest commit "e18781c63795d1202c80cdcb2f3ab007517e2356"
I see some dropout in our lidar scans. We have an OS0 (512X10 - LEGACY mode). Any ideas why this is happening?

**Comment by Samahu** [comment]
I think you would need to provide more details.

What is the platform (machine + operating system) are you running the driver on? which firmware version? how are you connected to the sensor?

**Comment by SFakoorian0111** [comment]
Thanks. we figured out the issue. It was something with our side that was causing the overload the network and dropping the lidar msgs. All is good on your end. 
But to answer your question, we are using a CPU (intel Ruby) in which the lidar is connected via Ethernet port to it.
