### ISSUE TITLE
ROS2 how is header.stamp assigned in each /ouster/points message?

### ISSUE THREAD

**Issue by JeffR1992** [ouster-lidar/ouster-ros#89]
I wanted to ask how the ROS2 driver calculates the `header.stamp` field for each `/ouster/points` PointCloud2 message. Is this field set to the timestamp of the first point in the cloud, the last point in the cloud, or is it assigned in some other way (e.g. `header.stamp` is set to the time just before the PointCloud2 message is published by the ROS2 driver)?

Any links to code showing where the assignment of `header.stamp` is being done would be appreciated. Thanks very much.

**Comment by Samahu** [comment]
The timestamp of the point cloud message is assigned to the time of the first measurement of the scan, regardless of the size of azimuth window.

In case of packets drop at the start of the lidar scan then the value of the first measurment is imputed(using linear interpolation). For more details refer to #67 

I am going to close this ticket but if you feel that I didn't address your question feel free to re-open.
