### ISSUE TITLE
message_filter.ApproximateTimeSynchronizer method is not able to invoke the callback function for Ouster os1 lidar and usb camera

### ISSUE THREAD

**Issue by deepumdev** [ouster-lidar/ouster-ros#91]
I am using the Ouster OS1 LIDAR with ROS Melodic. The ROS package is publishing the LIDAR data and I am able to view it in RViz. I want to calibrate and fuse the LIDAR data with data from a USB camera, so I have implemented the cv_camera ROS package for the camera and created a new package called calib. However, I am facing an issue where the message_filter.ApproximateTimeSynchronizer method is not able to invoke the callback function. The topics I am subscribing to are cv_camera/image_raw, cv_camera/camera_info, and ouster/points. When I try to echo the ouster/points topic, the timestamp is not showing. How can I synchronize the time between the data streams ?

I have given below the code used.

import rospy
import message_filters
from sensor_msgs.msg import Image, CameraInfo, PointCloud2

def callback(image_msg, camera_info_msg, lidar_msg):
    # Process synchronized data here

image_sub = message_filters.Subscriber('/cv_camera/image_raw', Image)
info_sub = message_filters.Subscriber('/cv_camera/camera_info', CameraInfo)
lidar_sub = message_filters.Subscriber('/ouster/points', PointCloud2)

ts = message_filters.ApproximateTimeSynchronizer([image_sub, info_sub, lidar_sub], 10, 0.1)
ts.registerCallback(callback)

rospy.init_node('sync_node')
rospy.spin()

**Comment by deepumdev** [comment]
> The timestamp should be included in the body of the **PointCloud2** messages. Can you show me the output you get when executing the command `rostopic echo --noarr /ouster/points`?

![Screenshot from 2023-03-30 10-08-30](https://user-images.githubusercontent.com/53249831/228731312-aff75a99-6c3f-4982-9f16-09eb9166e3de.png)

Kindly go through the attachment.  It has the time stamp. But my code doesn't able to invoke the callback function. Could you please help me to sort out it.

**Comment by marufino** [comment]
The timestamps don't match between your lidar data and camera data.

That's because the lidar is counting seconds from when it was turned on, and the camera is in ROS time

In the ouster sensor.launch file, set timestamp_mode to TIME_FROM_ROS_TIME and that should allow your timestamps to be close enough to be captured by the synchronizer

**Comment by Samahu** [comment]
> The timestamps don't match between your lidar data and camera data.
> 
> That's because the lidar is counting seconds from when it was turned on, and the camera is in ROS time
> 
> In the ouster sensor.launch file, set timestamp_mode to TIME_FROM_ROS_TIME and that should allow your timestamps to be close enough to be captured by the synchronizer

Good thought, this is likely the issue. @deepumdev When relying on **Time Synchronization** you need to handle make sure the included sensors are running in Sync (either using a dedicated PTP clock, or depend entirely on ROS time, and for that you would need `timestamp_mode:=TIME_FROM_ROS_TIME` to `sensor.launch` as @marufino suggested.

**Comment by deepumdev** [comment]
> The timestamps don't match between your lidar data and camera data.
> 
> That's because the lidar is counting seconds from when it was turned on, and the camera is in ROS time
> 
> In the ouster sensor.launch file, set timestamp_mode to TIME_FROM_ROS_TIME and that should allow your timestamps to be close enough to be captured by the synchronizer

Its working fine. Thank you.
